PolizaJuridica/Controllers/ReportesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using OfficeOpenXml;
using PolizaJuridica.Data;
using PolizaJuridica.ViewModels;

namespace PolizaJuridica.Controllers
{
    public class ReportesController : Controller
    {
        private readonly PolizaJuridicaDbContext _context;

        public ReportesController(PolizaJuridicaDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Ventas(DateTime FechaInicio, DateTime FechaFin, DateTime FechaInicioPoliza, DateTime FechaFinPoliza, int IdSolicitudInicio, int IdSolicitudFin, int IdPolizaInicio, int IdPolizafin)
        {
            //var usuarioid = Int32.Parse(User.FindFirst("Id").Value);
            //var area = User.FindFirst("Area").Value;
            List<ReporteVentasViewModel> exceles = new List<ReporteVentasViewModel>();
            List<Poliza> excel = new List<Poliza>();


            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("Polizas");

                if (FechaInicio.GetHashCode() != 0 && FechaFin.GetHashCode() != 0)
                {
                    excel = _context.Poliza.Include(p => p.FisicaMoral.Solicitud.Representante.Representacion).Where(s => s.FisicaMoral.Solicitud.SolicitudFechaSolicitud.Date.CompareTo(FechaInicio.Date) >= 0 &&
                       s.FisicaMoral.Solicitud.SolicitudFechaSolicitud.Date.CompareTo(FechaFin.Date) <= 0).ToList();
                }

                if (FechaInicioPoliza.GetHashCode() != 0 && FechaFinPoliza.GetHashCode() != 0)
                {
                    excel = _context.Poliza.Include(p => p.FisicaMoral.Solicitud.Representante.Representacion).Where(s => s.Creacion.Date.CompareTo(FechaInicioPoliza.Date) >= 0 &&
                       s.Creacion.Date.CompareTo(FechaFinPoliza.Date) <= 0).ToList();
                }

                if (IdSolicitudInicio > 0 && IdSolicitudFin > 0)
                {
                    excel = _context.Poliza.Include(p => p.FisicaMoral.Solicitud.Representante.Representacion).Where(s => s.FisicaMoral.SolicitudId >= IdSolicitudInicio && s.FisicaMoral.SolicitudId <= IdSolicitudFin).ToList();
                }

                if (IdPolizaInicio > 0 && IdPolizafin > 0)
                {
                    excel = _context.Poliza.Include(p => p.FisicaMoral.Solicitud.Representante.Representacion).Where(s => s.PolizaId >= IdPolizaInicio && s.PolizaId <= IdPolizafin).ToList();
                }

                exceles = ReporteVentas(excel);

                worksheet.Cells.LoadFromCollection(exceles, true);

                package.Workbook.Calculate();
                var excelData = package.GetAsByteArray();
                var contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                var fileName = "Polizas.xlsx";
                return File(excelData, contentType, fileName);
            }
        }

        private List<ReporteVentasViewModel> ReporteVentas(List<Poliza> poliza)
        {
            List<ReporteVentasViewModel> rvv = new List<ReporteVentasViewModel>();
            foreach (var p in poliza)
            {

                try
                {

                    ReporteVentasViewModel rv = new ReporteVentasViewModel();
                    StructMovimiento sm = MovimientoMaestro(p.PolizaId);
                    rv.SolicitudId = p.FisicaMoral.SolicitudId;
                    var usuarioSolicitud = _context.UsuariosSolicitud.Include(us => us.Usuarios).Where(us => us.SolicitudId == rv.SolicitudId).ToList();
                    rv.PolizaId = p.PolizaId;
                    rv.Representacion = p.FisicaMoral.Solicitud.Representante == null ? "" : p.FisicaMoral.Solicitud.Representante.Representacion.RepresentacionNombre;
                    rv.Ejecutivo = p.FisicaMoral.Solicitud.Representante == null ? "" : p.FisicaMoral.Solicitud.Representante.UsuarioNomCompleto;
                    rv.Ubicacion = p.FisicaMoral.Solicitud.SolicitudUbicacionArrendado;
                    rv.Renovacion = p.FisicaMoral.Solicitud.IsRenovacion.ToString();
                    rv.PrecioPoliza = _context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 2).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault() == null ? 0 : (Decimal)_context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 2).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault().Importe;//p.FisicaMoral.Solicitud.CentroCostosId == null ? (Decimal)p.FisicaMoral.Solicitud.CostoPoliza : _context.CentroCostos.SingleOrDefault(c => c.CentroCostosId == p.FisicaMoral.Solicitud.CentroCostosId).CentroCostosMonto;
                    rv.PrecioSinIVA = rv.PrecioPoliza / Convert.ToDecimal(1.16);
                    rv.IVA = rv.PrecioPoliza - rv.PrecioSinIVA;
                    rv.IVAConcepto = _context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 13).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault() == null ? 0 : (Decimal)_context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 13).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault().Importe;
                    rv.Descuento = _context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 18).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault() == null ? 0 : (Decimal)_context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 18).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault().Importe;
                    rv.ImporteCobrado = TotalImporteCobrado(p.PolizaId, rv.PrecioPoliza, rv.IVAConcepto, rv.Descuento);
                    rv.ComisionAsesor = _context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 4).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault() == null ? 0 : (Decimal)_context.DetallePoliza.Where(po => p.PolizaId == po.PolizaId && po.CategoriaEsid == 4).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault().Importe;
                    rv.Anticipo = _context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 17).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault() == null ? 0 : (Decimal)_context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 17).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault().Importe;
                    rv.IngresoRepresentacion = _context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 3).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault() == null ? 0 : (Decimal)_context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 3).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault().Importe; ;
                    rv.Regalias = sm.Entrada > 0 ? ImporteCobrado(p.PolizaId) : 0;
                    rv.ComisionEjecutivo = _context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 7).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault() == null ? 0 : (Decimal)_context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 7).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault().Importe;
                    rv.Firma = _context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 9).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault() == null ? 0 : (Decimal)_context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 9).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault().Importe;
                    rv.Translados = _context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 6).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault() == null ? 0 : (Decimal)_context.DetallePoliza.Where(po => po.PolizaId == p.PolizaId && po.CategoriaEsid == 6).OrderByDescending(or => or.DetallePolizaId).FirstOrDefault().Importe;
                    rv.OtrosOperativos = OtrosMovimientos(p.PolizaId);
                    rv.ReciboId = sm.ReciboId;
                    rv.FechaCobro = sm.FechaConcluido.ToString() == "1/1/0001 12:00:00 AM" ? "" : sm.FechaConcluido.ToString();
                    rv.Asesor = Asesor(p.FisicaMoral.Solicitud);
                    rv.Capturada =  usuarioSolicitud.FirstOrDefault(us => us.Usuarios.AreaId == 10) == null ? "": usuarioSolicitud.FirstOrDefault(us => us.Usuarios.AreaId == 10).Usuarios.UsuarioNomCompleto;
                    rv.Investigada = usuarioSolicitud.FirstOrDefault(us => us.Usuarios.AreaId == 11) == null ? "": usuarioSolicitud.FirstOrDefault(us => us.Usuarios.AreaId == 11).Usuarios.UsuarioNomCompleto;
                    rv.Abogada = usuarioSolicitud.FirstOrDefault(us => us.Usuarios.AreaId == 12) == null ? "" : usuarioSolicitud.FirstOrDefault(us => us.Usuarios.AreaId == 12).Usuarios.UsuarioNomCompleto;
                    rv.EstatusPoliza = _context.UsuarioPoliza.Include(po => po.TipoProcesoPo).Where(s => s.PolizaId == p.PolizaId).OrderByDescending(o => o.UsuarioPolizaId).FirstOrDefault().TipoProcesoPo.Descripcion;
                    rv.EstatusSolicitud = _context.UsuariosSolicitud.Include(us => us.TipoProceso).Where(us => us.SolicitudId == p.FisicaMoral.SolicitudId).OrderByDescending(us => us.UsuariosSolicitudId).FirstOrDefault().TipoProceso.Descripcion;
                    Console.WriteLine(rv.PolizaId.ToString());
                    rvv.Add(rv);

                }
                catch (Exception e)
                {
                    Log log = new Log()
                    {
                        LogObjetoIn = "",

PolizaJuridica/Views/Reportes/Index.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-icon" data-background-color="green">
                <i class="material-icons">assignment</i>
            </div>
            <div class="card-content">
                <h4 class="card-title">Reporte de Ventas</h4>
                <div class="toolbar">
                    <div class="row">
                        @using (Html.BeginForm("ventas", "Reportes", FormMethod.Post))
                        {
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Fecha Inicio Solicitud</label>
                                        <input name="FechaInicio" class="form-control" type="date">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Fecha Fin Solicitud</label>
                                        <input name="FechaFin" class="form-control" type="date">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Fecha Inicio Poliza</label>
                                        <input name="FechaInicioPoliza" class="form-control" type="date">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Fecha Fin Poliza</label>
                                        <input name="FechaFinPoliza" class="form-control" type="date">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Id Solicitud</label>
                                        <input name="IdSolicitudInicio" class="form-control" type="number">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Hasta Id de Solicitud</label>
                                        <input name="IdSolicitudFin" class="form-control" type="number">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Id de Poliza</label>
                                        <input name="IdPolizaInicio" class="form-control" type="number">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">hasta Id Poliza</label>
                                        <input name="IdPolizafin" class="form-control" type="number">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <input type="reset" class='btn btn-fill btn-danger btn-wd' value="Limpiar">
                                        <input type="submit" class='btn btn-fill btn-primary btn-wd' value="Generar">
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
                <!-- end content-->
            </div>
            <!--  end card  -->
        </div>
        <!-- end col-md-12 -->
    </div>
</div>
<!-- end row -->
@section Scripts
    {
    <script type="text/javascript">

    </script>
}